f = open(r'C:\Users\dan-1\Desktop\Pr_2035\KDD_Python_58-4\Lessons\4\text.txt', "r")
# a = f.read()
# print(type(a))
print(f.readline(), end = "")
print(f.readline(), end = "")
print(f.readline())
print(f.readline())
# print(f.readlines())

# print("Hello!\n")
f.close()